create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  numbers jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.lotto_draws enable row level security;

revoke all on table public.lotto_draws from anon, authenticated;
grant select, insert, update, delete on table public.lotto_draws to service_role;

-- Optional future policy if you ever switch to authenticated user access:
-- create policy "authenticated can read lotto draws"
-- on public.lotto_draws
-- for select
-- to authenticated
-- using (true);
